name: Vibeology
favicon: null
layout_spectrum: 0.6375836408697069
typography_spectrum: 0.40027535730041564
title: The New Book of Names by Locq Fortune
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#da3833'
    - '#020202'
    - '#3b5b74'
    - '#b3b3b3'
  brandStrength: 0.5
  lightness: 0.09882337134331465
  saturation: 0.7427591877058148
  rhythmicContrast: 0.33621931029483676
purpose: []
